esphome:
  name: charagetemphumsensor
  friendly_name: CharageTempHumSensor

esp8266:
  board: esp01_1m

# Enable logging
logger:

#api:
#  encryption:
#    key: "bNzaaz+Fv0myDOQqrAU1bE/M1k7oEgoNSYzHUgwBsJM="

ota:
  - platform: esphome
    password: "189c975e5923c25be23adcff98954588"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Charagetemphumsensor"
    password: "vzGPJUeaHrEE"

captive_portal:

time:
  - platform: sntp

# Example configuration entry
wireguard:
  address: 10.0.0.1
  private_key: !secret wg_privkey
  peer_endpoint: smiousse.ddns.net
  peer_public_key: !secret wg_pubkey
  netmask: 0.0.0.0
  peer_port: 51820
  peer_persistent_keepalive: 25s

mqtt:
  broker: 192.168.2.166
  username: charage
  password: !secret mqtt_password
  keepalive: 60s
  
i2c:
  sda: 4
  scl: 5

# Example configuration entry
sensor:
  - platform: bme280_i2c
    temperature:
      name: "Charage Temperature"
      oversampling: 16x
    pressure:
      name: "Charage Pressure"
    humidity:
      name: "Charage Humidity"
    address: 0x76
    update_interval: 30s   