esphome:
  name: charagemaisontemphumsensor
  friendly_name: CharageMaisonTempHumSensor

esp8266:
  board: d1

# Enable logging
logger:

# Enable Home Assistant API
#api:
#  encryption:
#    key: "WPwyotHVbgfPod1heS7zQ9Kn706rp6LmB3yGAvLAAgo="

ota:
  - platform: esphome
    password: "b98b7461f7899d2c73e72d2020028a50"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Charagemaisontemphumsensor"
    password: "wmQzXUNcTEQa"

captive_portal:

mqtt:
  broker: 192.168.1.147
  port: 11883

sensor:
  - platform: dht
    pin: D5
    temperature:
      name: "Charage Maison Temperature"
    humidity:
      name: "Charage Maison Humidity"
    update_interval: 60s
    model: DHT11