esphome:
  name: dommariewaterlevelsensor
  friendly_name: DomMarieWaterLevelSensor

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
#api:
#  encryption:
#    key: "qhGPHfkltIKShwtNlzDVnldqkoqVDeMOwLNcZX/tMxg="

ota:
  - platform: esphome
    password: "8968acc7a4bee4269cff3f1e583c4b5e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dommariewaterlevelsensor"
    password: "m9uM8Qpapy2w"

captive_portal:

mqtt:
  broker: 192.168.1.147
  port: 11883

sensor:
  - platform: adc
    pin: A0
    id: dommarie_water_sensor_volt
    name: "DomMarie - Water Sensor Volt"
    update_interval: 60s
    accuracy_decimals: 5    
    unit_of_measurement: 'V'
  
  - platform: template
    name: "DomMarie - Niveau d'eau"
    id: dommarie_water_level
    unit_of_measurement: "%"    
    filters:
      - calibrate_linear:
          - 0.0136 -> 0.0
          - 1 -> 100   
    icon: "mdi:water-percent"
    update_interval: 60s
    accuracy_decimals: 1
    lambda: |-
      return id(dommarie_water_sensor_volt).state;   