esphome:
  name: garagetemphumsensor
  platform: ESP8266
  board: nodemcu

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "qvgR0ya4AiY1ASRVXLt7mgCEV/boa1oo1OylZotgMeQ="

ota:
  - platform: esphome
    password: "4707e626e3368a156a0dacdaff008e32"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garagetemphumsensor"
    password: "ybkBuduVpB2K"

captive_portal:
  
i2c:
  sda: 4
  scl: 5

# Example configuration entry
sensor:
  - platform: bme280_i2c
    temperature:
      name: "Garage Temperature"
      oversampling: 16x
    pressure:
      name: "Garage Pressure"
    humidity:
      name: "Garage Humidity"
    address: 0x76
    update_interval: 60s   