esphome:
  name: sallejeuxtemphumsensor
  friendly_name: SalleJeuxTempHumSensor

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "FmlAuwh1sPCC2k12JMQGhYGgf3GGXSYFUAKDvuNVrFc="

ota:
  - platform: esphome
    password: "aba8092c707fed7a5dfc3fd63c8c6b11"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sallejeuxtemphumsensor"
    password: "maHeeq6LMzBo"

captive_portal:
    
i2c:
  sda: 4
  scl: 5

# Example configuration entry
sensor:
  - platform: bme280_i2c
    temperature:
      name: "Salle de Jeux Temperature"
      oversampling: 16x
    pressure:
      name: "Salle de Jeux Pressure"
    humidity:
      name: "Salle de Jeux Humidity"
    address: 0x76
    update_interval: 60s  
  - platform: adc
    pin: A0
    id: home_basement_water_sensor_volt
    name: "Sous-sol - Water Sensor Volt"
    update_interval: 10s
    accuracy_decimals: 5    
    unit_of_measurement: 'V'
  
  - platform: template
    name: "Sous-sol - Niveau d'eau"
    id: home_basement_water_level
    unit_of_measurement: "%"    
    filters:
      - calibrate_linear:
          - 0.0035 -> 0.0
          - 1 -> 100   
    icon: "mdi:water-percent"
    update_interval: 10s
    accuracy_decimals: 1
    lambda: |-
      return id(home_basement_water_sensor_volt).state;   